version: '3'

services:
  visual-app:
    build: .
    container_name: visual-app
    ports:
      - '8501:8501'
    volumes:
      - ${PWD}/app.py:/app/app.py
    command: ["streamlit", "run", "app.py"]


